[package]
name = "contrib"
version = "1.0.0"
authors = ["Florian Gauger <flo.gauger@gmail.com>"]
edition = "2018"

[dependencies]
graphql_client = "0.6.1"
serde = "1.0.87"
serde_derive = "1.0.87"
reqwest = "0.9.9"
serde_json = "1.0"
log = "0.4.6"
env_logger = "0.6.0"
rand = "0.6.5"

